---
- hosts: consul_nodes, vault
  remote_user: ec2-user
  become: yes
  gather_facts: True
  roles:
    - {role: consul}
- hosts: vault
  remote_user: ec2-user
  become: yes
  gather_facts: True
  roles:
    - {role: vault}
